name: SQL Lint and Pattern Check

on:
  workflow_dispatch:
 

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SQLFluff
        run: |
          pip install sqlfluff

      - name: Lint SQL files
        run: |
          sqlfluff lint '**/*.sql' --dialect ansi

      - name: Search for environment patterns
        run: |
          if grep -rnw '.' -e '@dev@' -e '@test@' -e '@prod@'; then
            echo "❌ Environment pattern found. Failing the workflow."
            exit 1
          else
            echo "✅ No environment patterns found."
          fi
