CREATE ICEBERG TABLE IF NOT EXISTS ULU_DB_SIT.IIPAS.TABLE5 (
    INSUP_FLAG STRING COMMENT 'INSERT and UPDATE Flag',
    SETID STRING COMMENT '',
    MODIFIED_TIMESTAMP TIMESTAMP
)
COMMENT = ''
CATALOG = 'SNOWFLAKE'
EXTERNAL_VOLUME = 'ULUDM_DEV_EXT_VOL_SILVER_ICEBERG_EXVOL'
BASE_LOCATION = 'oeds/ar_action_lst';
